platform :ios, '7.0'

target 'quchuxing' do

pod 'AFNetworking', '~> 3.2.1'

pod 'SDWebImage', '~> 4.0'

pod 'MJRefresh'

pod 'Masonry'

pod 'JSONModel'

pod 'MBProgressHUD'

pod 'UMCCommon'
pod 'UMCSecurityPlugins'

# U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMCShare/UI'

# 集成微信(精简版0.2M)
    pod 'UMCShare/Social/ReducedWeChat'

# 集成QQ/QZone/TIM(精简版0.5M)
    pod 'UMCShare/Social/ReducedQQ'

# 集成新浪微博(精简版1M)
    pod 'UMCShare/Social/ReducedSina'

pod 'WechatOpenSDK'

pod 'AMapLocation'

end



